/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constants */
        get: operations["constants_api_v1_constants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/palette": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Palette */
        get: operations["palette_api_v1_palette_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate/module-powers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Module Powers String */
        post: operations["validate_module_powers_string_api_v1_validate_module_powers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate/car-ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Car Ports */
        post: operations["validate_car_ports_api_v1_validate_car_ports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate/system-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate System Config Endpoint */
        post: operations["validate_system_config_endpoint_api_v1_validate_system_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/topology/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_topology_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute
         * @description Stateless recompute — used by the UI for instant FR-09 feedback.
         */
        post: operations["compute_api_v1_snapshot_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Snapshot */
        get: operations["session_snapshot_api_v1_sessions__session_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/apply-and-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply And Generate
         * @description FR-14: produce the Present → Target control-step sequence and store it.
         */
        post: operations["apply_and_generate_api_v1_sessions__session_id__apply_and_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/control-steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Control Steps
         * @description FR-15: return the stored sequence for the player.
         */
        get: operations["get_control_steps_api_v1_sessions__session_id__control_steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Step
         * @description FR-15 player: advance forward or back, with end-of-sequence wrap.
         *
         *     - Forward past last step → wraps to step 0 (Initial State).
         *     - Back past first step (0) → wraps to last step.
         *     - Forward when no steps exist → stays at 0.
         */
        post: operations["advance_step_api_v1_sessions__session_id__step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CarPortBatchRaw */
        CarPortBatchRaw: {
            /** Ports */
            ports: components["schemas"]["RawCarPortInput"][];
        };
        /** CarPortBatchValidateRequest */
        CarPortBatchValidateRequest: {
            batch: components["schemas"]["CarPortBatchRaw"];
            system_config?: components["schemas"]["SystemConfig"] | null;
        };
        /** CarPortBatchValidateResponse */
        CarPortBatchValidateResponse: {
            /** Ports */
            ports: components["schemas"]["CarPortInput"][];
            /** Warnings */
            warnings: components["schemas"]["WarningDetail"][];
            /** Errors */
            errors: components["schemas"]["ErrorDetail"][];
            /**
             * Apply Ready
             * @description True iff at least 2 ports have priority set (FR-16 precondition).
             */
            apply_ready: boolean;
        };
        /**
         * CarPortInput
         * @description Canonical (already-validated) per-port state.
         *
         *     Values must already be clamped to [0, 600] and aligned to 25 kW. Use
         *     ``validation_service.normalize_car_port`` to accept raw user input and
         *     produce a ``CarPortInput`` plus warnings.
         */
        CarPortInput: {
            /**
             * Port Id
             * @description 1-based Car Port id (1..2N).
             */
            port_id: number;
            /** Max Required */
            max_required: number;
            /**
             * Present
             * @default 0
             */
            present: number;
            /**
             * Target
             * @default 0
             */
            target: number;
            /**
             * Priority
             * @description Unique priority 1..N; lower = higher priority (FR-16).
             */
            priority?: number | null;
        };
        /**
         * CarSnapshot
         * @description FR-05: car icon color based on Output Relay state & Max Required.
         */
        CarSnapshot: {
            /** Port Id */
            port_id: number;
            /**
             * Rec Bd Id
             * @description Home REC BD id = ceil(port_id/2).
             */
            rec_bd_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "Active" | "Inactive";
            /** Color */
            color: string;
            /** Max Required */
            max_required: number;
            /**
             * Allocated Kw
             * @description Actual kW allocated by this snapshot (may be < max_required on capacity shortage).
             */
            allocated_kw: number;
            /** Priority */
            priority?: number | null;
        };
        /** ControlStep */
        ControlStep: {
            /** Step Index */
            step_index: number;
            /** Description */
            description: string;
            snapshot: components["schemas"]["VisualSnapshot"];
        };
        /** ControlStepSequence */
        ControlStepSequence: {
            /** Total Steps */
            total_steps: number;
            /** Steps */
            steps?: components["schemas"]["ControlStep"][];
            initial_state: components["schemas"]["VisualSnapshot"];
            /** Warnings */
            warnings?: string[];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Machine-readable error code (e.g. 'MAX_REQUIRED_OUT_OF_RANGE').
             */
            code: string;
            /**
             * Field
             * @description Dotted path to the offending field (e.g. 'car_ports[2].max_required').
             */
            field?: string | null;
            /**
             * Message
             * @description Human-readable error message.
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModuleGroupView */
        ModuleGroupView: {
            /**
             * Group Index
             * @description 0-based position within the REC BD (0..3 for default 4-module layout).
             */
            group_index: number;
            /** Power Kw */
            power_kw: number;
            /**
             * Pack Count
             * @description power_kw // 25 (FR-11: 50→2, 75→3, 100→4).
             */
            pack_count: number;
            /**
             * Pack Indices
             * @description Global 0-based pack indices within this REC BD that this group covers.
             */
            pack_indices: number[];
        };
        /** ModulePowerStringRequest */
        ModulePowerStringRequest: {
            /**
             * Raw
             * @description Comma-separated module powers, e.g. '50, 75, 75, 50'.
             */
            raw: string;
        };
        /** ModulePowerStringResponse */
        ModulePowerStringResponse: {
            /** Powers */
            powers: number[];
            /** Total Capacity Kw */
            total_capacity_kw: number;
            /** Pack Count */
            pack_count: number;
            /** Errors */
            errors: components["schemas"]["ErrorDetail"][];
        };
        /**
         * PackSnapshot
         * @description FR-03: one 25 kW pack. Color = consuming port's *home* REC BD color (or idle grey).
         */
        PackSnapshot: {
            /**
             * Rec Bd Id
             * @description REC BD the pack physically lives in.
             */
            rec_bd_id: number;
            /**
             * Pack Index
             * @description 0-based index within the REC BD.
             */
            pack_index: number;
            /** In Use */
            in_use: boolean;
            /**
             * Owner Port Id
             * @description Port consuming this pack, if any.
             */
            owner_port_id?: number | null;
            /** Color */
            color: string;
        };
        /**
         * RawCarPortInput
         * @description Untrusted input direct from the UI — values may be out of range or not 25 kW aligned.
         *
         *     Used by the validation endpoint; the normalizer clamps & rounds, emitting warnings.
         */
        RawCarPortInput: {
            /** Port Id */
            port_id: number;
            /** Max Required */
            max_required: number;
            /**
             * Present
             * @default 0
             */
            present: number;
            /**
             * Target
             * @default 0
             */
            target: number;
            /** Priority */
            priority?: number | null;
        };
        /**
         * RecBdConfig
         * @description One REC BD's module-power list (FR-11). Each module is 50~100 kW, multiple of 25.
         */
        RecBdConfig: {
            /**
             * Id
             * @description 1-based REC BD id.
             */
            id: number;
            /**
             * Module Powers
             * @description Per-module power in kW, e.g. [50, 75, 75, 50].
             */
            module_powers: number[];
        };
        /**
         * RecBdSnapshot
         * @description FR-02: per-REC-BD live power + status.
         */
        RecBdSnapshot: {
            /** Id */
            id: number;
            /** Color */
            color: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Occupied" | "Idle";
            /** Power Kw */
            power_kw: number;
            /** Used Packs */
            used_packs: number;
            /** Total Packs */
            total_packs: number;
        };
        /** RecBdView */
        RecBdView: {
            /** Id */
            id: number;
            /**
             * Color
             * @description Identification color from the palette (FR-01).
             */
            color: string;
            /** Total Capacity Kw */
            total_capacity_kw: number;
            /** Pack Count */
            pack_count: number;
            /** Modules */
            modules: components["schemas"]["ModuleGroupView"][];
            /**
             * Inter Group Relay Ids
             * @description e.g. ['M1.R2','M1.R3','M1.R4'] for 4-module REC BD.
             */
            inter_group_relay_ids: string[];
            /**
             * Output Relay Ids
             * @description e.g. ['M1.O1','M1.O2'].
             */
            output_relay_ids: string[];
            /**
             * Car Port Ids
             * @description Two port ids housed on this REC BD (CAR_PORTS_PER_REC_BD=2).
             */
            car_port_ids: number[];
        };
        /**
         * RelaySnapshot
         * @description FR-04: output / inter-group / bridge relay state.
         */
        RelaySnapshot: {
            /**
             * Id
             * @description 'M1.O1', 'M1.R2', or 'B_1_2'.
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "output" | "inter_group" | "bridge";
            /**
             * State
             * @enum {string}
             */
            state: "Closed" | "Open";
            /** Color */
            color: string;
            /**
             * Owner Port Id
             * @description Output relays only: the port they feed.
             */
            owner_port_id?: number | null;
            /**
             * Rec Bd Id
             * @description Output / inter_group relays: their home REC BD.
             */
            rec_bd_id?: number | null;
        };
        /** SessionCreateRequest */
        SessionCreateRequest: {
            system_config: components["schemas"]["SystemConfig"];
            /** Car Ports */
            car_ports?: components["schemas"]["CarPortInput"][] | null;
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            system_config: components["schemas"]["SystemConfig"];
            /** Car Ports */
            car_ports?: components["schemas"]["CarPortInput"][];
            /**
             * Mode
             * @default edit
             * @enum {string}
             */
            mode: "edit" | "player";
            step_sequence?: components["schemas"]["ControlStepSequence"] | null;
            /**
             * Current Step Index
             * @default 0
             */
            current_step_index: number;
        };
        /** SessionUpdateRequest */
        SessionUpdateRequest: {
            system_config?: components["schemas"]["SystemConfig"] | null;
            /** Car Ports */
            car_ports?: components["schemas"]["CarPortInput"][] | null;
        };
        /** SnapshotComputeRequest */
        SnapshotComputeRequest: {
            system_config: components["schemas"]["SystemConfig"];
            /** Car Ports */
            car_ports: components["schemas"]["CarPortInput"][];
            /**
             * Cycle Palette
             * @default true
             */
            cycle_palette: boolean;
        };
        /** StepPlayerView */
        StepPlayerView: {
            /** Current Step Index */
            current_step_index: number;
            /** Total Steps */
            total_steps: number;
            snapshot: components["schemas"]["VisualSnapshot"];
            /** Description */
            description: string;
        };
        /**
         * SystemConfig
         * @description Top-level charging-station configuration (FR-10).
         */
        SystemConfig: {
            /** Rec Bd Count */
            rec_bd_count: number;
            /** Rec Bds */
            rec_bds: components["schemas"]["RecBdConfig"][];
        };
        /** SystemConfigValidateResponse */
        SystemConfigValidateResponse: {
            /** Errors */
            errors: components["schemas"]["ErrorDetail"][];
            /** Total Capacity Kw */
            total_capacity_kw: number;
            /** Car Port Count */
            car_port_count: number;
        };
        /** TopologyPreview */
        TopologyPreview: {
            /** Rec Bd Count */
            rec_bd_count: number;
            /** Car Port Count */
            car_port_count: number;
            /** Total Capacity Kw */
            total_capacity_kw: number;
            /** Rec Bds */
            rec_bds: components["schemas"]["RecBdView"][];
            /**
             * Bridge Relay Ids
             * @description Between-REC-BD bridges. 0 when N=1, 1 when N=2 (linear), N when N>=3 (ring).
             */
            bridge_relay_ids: string[];
        };
        /** TopologyPreviewRequest */
        TopologyPreviewRequest: {
            system_config: components["schemas"]["SystemConfig"];
            /**
             * Cycle Palette
             * @description Use 4-color cycle (FR-10) vs extended palette.
             * @default true
             */
            cycle_palette: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisualSnapshot
         * @description FR-09 emits one of these per change.
         */
        VisualSnapshot: {
            /** Rec Bds */
            rec_bds?: components["schemas"]["RecBdSnapshot"][];
            /** Packs */
            packs?: components["schemas"]["PackSnapshot"][];
            /** Relays */
            relays?: components["schemas"]["RelaySnapshot"][];
            /** Cars */
            cars?: components["schemas"]["CarSnapshot"][];
            /**
             * Total Power Kw
             * @default 0
             */
            total_power_kw: number;
            /**
             * Total Requested Kw
             * @default 0
             */
            total_requested_kw: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * WarningDetail
         * @description Non-blocking advisory — e.g. input was clamped or rounded per FR-12.
         */
        WarningDetail: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Original Value */
            original_value?: number | null;
            /** Adjusted Value */
            adjusted_value?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    constants_api_v1_constants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    palette_api_v1_palette_get: {
        parameters: {
            query?: {
                count?: number;
                /** @description Use the 4-color cycle (FR-10) vs. the extended palette. */
                cycle?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_module_powers_string_api_v1_validate_module_powers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModulePowerStringRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulePowerStringResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_car_ports_api_v1_validate_car_ports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarPortBatchValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarPortBatchValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_system_config_endpoint_api_v1_validate_system_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_topology_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopologyPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_api_v1_snapshot_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotComputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_snapshot_api_v1_sessions__session_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_and_generate_api_v1_sessions__session_id__apply_and_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlStepSequence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_control_steps_api_v1_sessions__session_id__control_steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlStepSequence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_step_api_v1_sessions__session_id__step_post: {
        parameters: {
            query?: {
                direction?: "forward" | "back";
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepPlayerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
